# jekyll configuration

title: "Transfuse"

currentVersion: "0.3.0-beta-13"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks!

# end of configuration
